[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.0"

# [profile.solc_0_6]
# version = "0.6.0"
# path = ["src/v_0.6.0"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
